---
# tasks file for app


- name: ansible create directory example
  file:
    path: /infra_check_tmp
    state: directory

- name: Transfer the script
  copy: src=files/InfraCheckServer.py  dest=/infra_check_tmp mode=0777

- name: Starting required ports
  shell: nohup python /infra_check_tmp/InfraCheckServer.py {{ports}} {{protocol}} {{server}}
  register: output
  failed_when: output.stderr | length > 0 

- debug:
    msg: "{{output}}"
  when: output.stderr | length == 0 
